@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"

rem Create output directories
if not exist "build" mkdir "build"
if not exist "build/test/unit" mkdir "build/test/unit"

pushd "configs" && cp linux.config ../build/tup.config && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/main.cpp /Fobuild/main.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/platform/path-win32.cpp /Fobuild/path-win32.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/platform/env-win32.cpp /Fobuild/env-win32.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/platform/file_io-win32.cpp /Fobuild/file_io-win32.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/platform/process-win32.cpp /Fobuild/process-win32.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/platform/async_process-win32.cpp /Fobuild/async_process-win32.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/target.cpp /Fobuild/target.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/output.cpp /Fobuild/output.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/options.cpp /Fobuild/options.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/multi_variant.cpp /Fobuild/multi_variant.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/context.cpp /Fobuild/context.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/config_commands.cpp /Fobuild/config_commands.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/cmd_parse.cpp /Fobuild/cmd_parse.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/cmd_show.cpp /Fobuild/cmd_show.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/cmd_configure.cpp /Fobuild/cmd_configure.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/cmd_clean.cpp /Fobuild/cmd_clean.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/cli/cmd_build.cpp /Fobuild/cmd_build.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/exec/scheduler.cpp /Fobuild/scheduler.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/exec/runner.cpp /Fobuild/runner.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/exec/progress_display.cpp /Fobuild/progress_display.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/index/writer.cpp /Fobuild/writer.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/index/reader.cpp /Fobuild/reader.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/index/entry.cpp /Fobuild/entry.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/topo.cpp /Fobuild/topo.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/scanners/gcc.cpp /Fobuild/gcc.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/rule_pattern.cpp /Fobuild/rule_pattern.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/dep_scanner.cpp /Fobuild/dep_scanner.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/dag.cpp /Fobuild/dag.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/graph/builder.cpp /Fobuild/builder.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/var_tracking.cpp /Fobuild/var_tracking.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/parser.cpp /Fobuild/parser.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/lexer.cpp /Fobuild/lexer.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/ignore.cpp /Fobuild/ignore.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/glob.cpp /Fobuild/glob.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/eval.cpp /Fobuild/eval.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/depfile.cpp /Fobuild/depfile.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/config.cpp /Fobuild/config.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/parser/ast.cpp /Fobuild/ast.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/terminal.cpp /Fobuild/terminal.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/string_utils.cpp /Fobuild/string_utils.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/string_pool.cpp /Fobuild/string_pool.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/path_utils.cpp /Fobuild/path_utils.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/metrics.cpp /Fobuild/metrics.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/layout.cpp /Fobuild/layout.obj && popd || exit /b 1
pushd "." && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I./include -I./third_party  /O2 /DNDEBUG /Gy /Gw /c src/core/hash.cpp /Fobuild/hash.obj && popd || exit /b 1
pushd "." && cl /std:c11 /W4 /WX /nologo -I./third_party  /O2 /Gy /WX- /c third_party/sha256/sha256.c /Fobuild/sha256.obj && popd || exit /b 1
pushd "." && link /nologo build/sha256.obj build/hash.obj build/layout.obj build/metrics.obj build/path_utils.obj build/string_pool.obj build/string_utils.obj build/terminal.obj build/ast.obj build/config.obj build/depfile.obj build/eval.obj build/glob.obj build/ignore.obj build/lexer.obj build/parser.obj build/var_tracking.obj build/builder.obj build/dag.obj build/dep_scanner.obj build/rule_pattern.obj build/gcc.obj build/topo.obj build/entry.obj build/reader.obj build/writer.obj build/progress_display.obj build/runner.obj build/scheduler.obj build/cmd_build.obj build/cmd_clean.obj build/cmd_configure.obj build/cmd_show.obj build/cmd_parse.obj build/config_commands.obj build/context.obj build/multi_variant.obj build/options.obj build/output.obj build/target.obj build/async_process-win32.obj build/process-win32.obj build/file_io-win32.obj build/env-win32.obj build/path-win32.obj build/main.obj /OUT:build/putup.exe /OPT:REF /OPT:ICF  && popd || exit /b 1
pushd "." && lib /nologo /OUT:build/libputup.lib build/sha256.obj build/hash.obj build/layout.obj build/metrics.obj build/path_utils.obj build/string_pool.obj build/string_utils.obj build/terminal.obj build/ast.obj build/config.obj build/depfile.obj build/eval.obj build/glob.obj build/ignore.obj build/lexer.obj build/parser.obj build/var_tracking.obj build/builder.obj build/dag.obj build/dep_scanner.obj build/rule_pattern.obj build/gcc.obj build/topo.obj build/entry.obj build/reader.obj build/writer.obj build/progress_display.obj build/runner.obj build/scheduler.obj build/cmd_build.obj build/cmd_clean.obj build/cmd_configure.obj build/cmd_show.obj build/cmd_parse.obj build/config_commands.obj build/context.obj build/multi_variant.obj build/options.obj build/output.obj build/target.obj build/async_process-win32.obj build/process-win32.obj build/file_io-win32.obj build/env-win32.obj build/path-win32.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_var_tracking.cpp /Fo../../build/test/unit/test_var_tracking.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_types.cpp /Fo../../build/test/unit/test_types.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_target.cpp /Fo../../build/test/unit/test_target.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_string_utils.cpp /Fo../../build/test/unit/test_string_utils.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_rule_pattern.cpp /Fo../../build/test/unit/test_rule_pattern.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_platform_process.cpp /Fo../../build/test/unit/test_platform_process.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_platform_file_io.cpp /Fo../../build/test/unit/test_platform_file_io.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_path_utils.cpp /Fo../../build/test/unit/test_path_utils.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_parser.cpp /Fo../../build/test/unit/test_parser.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_main.cpp /Fo../../build/test/unit/test_main.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_lexer.cpp /Fo../../build/test/unit/test_lexer.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_layout.cpp /Fo../../build/test/unit/test_layout.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_index.cpp /Fo../../build/test/unit/test_index.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_ignore.cpp /Fo../../build/test/unit/test_ignore.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_hash.cpp /Fo../../build/test/unit/test_hash.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_graph.cpp /Fo../../build/test/unit/test_graph.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_glob.cpp /Fo../../build/test/unit/test_glob.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_exec.cpp /Fo../../build/test/unit/test_exec.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_eval.cpp /Fo../../build/test/unit/test_eval.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_e2e.cpp /Fo../../build/test/unit/test_e2e.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_depfile.cpp /Fo../../build/test/unit/test_depfile.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_dep_scanner.cpp /Fo../../build/test/unit/test_dep_scanner.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_builder.cpp /Fo../../build/test/unit/test_builder.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c test_bench.cpp /Fo../../build/test/unit/test_bench.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /c e2e_fixture.cpp /Fo../../build/test/unit/e2e_fixture.obj && popd || exit /b 1
pushd "test/unit" && cl /std:c++20 /W4 /WX /nologo /EHsc /GR- /D_CRT_SECURE_NO_WARNINGS -I../../include -I../../third_party  /O2 /DNDEBUG /Gy /Gw /WX- /c ../../third_party/catch_amalgamated.cpp /Fo../../build/test/unit/catch_amalgamated.obj && popd || exit /b 1
pushd "test/unit" && link /nologo ../../build/test/unit/test_bench.obj ../../build/test/unit/test_builder.obj ../../build/test/unit/test_dep_scanner.obj ../../build/test/unit/test_depfile.obj ../../build/test/unit/test_e2e.obj ../../build/test/unit/test_eval.obj ../../build/test/unit/test_exec.obj ../../build/test/unit/test_glob.obj ../../build/test/unit/test_graph.obj ../../build/test/unit/test_hash.obj ../../build/test/unit/test_ignore.obj ../../build/test/unit/test_index.obj ../../build/test/unit/test_layout.obj ../../build/test/unit/test_lexer.obj ../../build/test/unit/test_main.obj ../../build/test/unit/test_parser.obj ../../build/test/unit/test_path_utils.obj ../../build/test/unit/test_platform_file_io.obj ../../build/test/unit/test_platform_process.obj ../../build/test/unit/test_rule_pattern.obj ../../build/test/unit/test_string_utils.obj ../../build/test/unit/test_target.obj ../../build/test/unit/test_types.obj ../../build/test/unit/test_var_tracking.obj ../../build/test/unit/catch_amalgamated.obj ../../build/test/unit/e2e_fixture.obj ../../build/libputup.lib /OUT:../../build/test/unit/putup_test.exe /OPT:REF /OPT:ICF  && popd || exit /b 1
