// SPDX-License-Identifier: MIT
// Copyright (c) 2024 pup authors

#include "pup/cli/commands.hpp"
#include "pup/cli/context.hpp"
#include "pup/cli/output.hpp"
#include "pup/core/layout.hpp"
#include "pup/core/string_utils.hpp"
#include "pup/core/types.hpp"
#include "pup/graph/dag.hpp"
#include "pup/graph/topo.hpp"

#include <cstdlib>
#include <set>

#include <fmt/core.h>

namespace pup::cli {

namespace {

auto cmd_export_script(Options const& opts) -> int
{
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fmt::print(stderr, "Error: {}\n", result.error().message);
        return EXIT_FAILURE;
    }

    auto& ctx = *result;
    auto topo = pup::graph::topological_sort(ctx.graph());

    fmt::print("#!/bin/sh\n");
    fmt::print("# Generated by pup\n");
    fmt::print("set -e\n");
    fmt::print("cd \"{}\"\n\n", ctx.layout().source_root.string());

    auto output_dirs = std::set<std::string> {};
    for (auto id : ctx.graph().all_nodes()) {
        auto const* node = ctx.graph().get_node(id);
        if (!node) {
            continue;
        }
        if (node->type != pup::NodeType::Generated && node->type != pup::NodeType::File) {
            continue;
        }

        auto node_path = ctx.graph().get_full_path(id);
        if (node_path.empty()) {
            continue;
        }

        auto inputs = ctx.graph().get_inputs(id);
        for (auto input_id : inputs) {
            auto const* input = ctx.graph().get_node(input_id);
            if (input && input->type == pup::NodeType::Command) {
                auto path = std::filesystem::path { node_path };
                if (path.has_parent_path()) {
                    auto parent = path.parent_path().string();
                    if (!parent.empty() && parent != ".") {
                        output_dirs.insert(parent);
                    }
                }
                break;
            }
        }
    }

    if (!output_dirs.empty()) {
        fmt::print("# Create output directories\n");
        for (auto const& dir : output_dirs) {
            fmt::print("mkdir -p \"{}\"\n", dir);
        }
        fmt::print("\n");
    }

    for (auto id : topo.order) {
        auto const* node = ctx.graph().get_node(id);
        if (!node || node->type != pup::NodeType::Command) {
            continue;
        }

        auto dir = node->source_dir.empty() ? std::string { "." } : node->source_dir;
        fmt::print("(cd \"{}\" && {})\n", dir, node->command);
    }

    return EXIT_SUCCESS;
}

auto cmd_export_graph(Options const& opts) -> int
{
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fmt::print(stderr, "Error: {}\n", result.error().message);
        return EXIT_FAILURE;
    }

    auto& ctx = *result;

    if (opts.summary) {
        auto commands = ctx.graph().nodes_of_type(pup::NodeType::Command);
        fmt::print("Tupfiles: {}\n", ctx.parsed_dirs().size());
        fmt::print("Nodes: {}\n", ctx.graph().node_count());
        fmt::print("Edges: {}\n", ctx.graph().edge_count());
        fmt::print("Commands: {}\n", commands.size());

        if (opts.verbose) {
            fmt::print("\nCommands:\n");
            for (auto id : commands) {
                if (auto const* node = ctx.graph().get_node(id)) {
                    auto display = node->display.empty() ? node->command : node->display;
                    fmt::print("  {}\n", display);
                }
            }
        }
        return EXIT_SUCCESS;
    }

    fmt::print("digraph G {{\n");
    fmt::print("  rankdir=LR;\n");

    for (auto id : ctx.graph().all_nodes()) {
        auto const* node = ctx.graph().get_node(id);
        if (!node) {
            continue;
        }

        auto label = escape_dot_label(
            node->type == pup::NodeType::Command
                ? (node->display.empty() ? node->command : node->display)
                : ctx.graph().get_full_path(id));

        fmt::print("  n{} [label=\"{}\"];\n", id, label);

        for (auto input_id : ctx.graph().get_inputs(id)) {
            fmt::print("  n{} -> n{};\n", input_id, id);
        }
    }

    fmt::print("}}\n");
    return EXIT_SUCCESS;
}

auto cmd_export_compdb(Options const& opts) -> int
{
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fmt::print(stderr, "Error: {}\n", result.error().message);
        return EXIT_FAILURE;
    }

    auto& ctx = *result;

    fmt::print("[\n");
    auto commands = ctx.graph().nodes_of_type(pup::NodeType::Command);
    auto first = true;

    for (auto id : commands) {
        auto const* node = ctx.graph().get_node(id);
        if (!node) {
            continue;
        }

        auto source_file = std::string {};
        for (auto input_id : ctx.graph().get_inputs(id)) {
            auto input_path = ctx.graph().get_full_path(input_id);
            if (input_path.empty()) {
                continue;
            }
            if (input_path.ends_with(".c") || input_path.ends_with(".cc") || input_path.ends_with(".cpp") || input_path.ends_with(".cxx") || input_path.ends_with(".C") || input_path.ends_with(".S") || input_path.ends_with(".s")) {
                source_file = std::move(input_path);
                break;
            }
        }

        auto output_file = std::string {};
        for (auto output_id : ctx.graph().get_outputs(id)) {
            auto output_path = ctx.graph().get_full_path(output_id);
            if (output_path.empty()) {
                continue;
            }
            if (output_path.ends_with(".o") || output_path.ends_with(".obj")) {
                output_file = std::move(output_path);
                break;
            }
        }

        if (source_file.empty()) {
            continue;
        }

        auto working_dir = ctx.layout().source_root;
        if (!node->source_dir.empty()) {
            working_dir /= node->source_dir;
        }

        auto args = pup::core::tokenize_shell_command(node->command);
        if (args.empty()) {
            continue;
        }

        if (!first) {
            fmt::print(",\n");
        }
        first = false;

        fmt::print("  {{\n");
        fmt::print("    \"directory\": \"{}\",\n", escape_json(working_dir.string()));

        fmt::print("    \"arguments\": [");
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (i > 0) {
                fmt::print(", ");
            }
            fmt::print("\"{}\"", escape_json(args[i]));
        }
        fmt::print("],\n");

        fmt::print("    \"file\": \"{}\"", escape_json(source_file));
        if (!output_file.empty()) {
            fmt::print(",\n    \"output\": \"{}\"", escape_json(output_file));
        }
        fmt::print("\n  }}");
    }

    fmt::print("\n]\n");
    return EXIT_SUCCESS;
}

} // namespace

auto cmd_export(Options const& opts) -> int
{
    if (opts.export_format.empty()) {
        fmt::print(stderr, "Usage: pup export <format>\n");
        fmt::print(stderr, "Formats: script, compdb, graph\n");
        return EXIT_FAILURE;
    }

    if (opts.export_format == "script") {
        return cmd_export_script(opts);
    }
    if (opts.export_format == "compdb") {
        return cmd_export_compdb(opts);
    }
    if (opts.export_format == "graph") {
        return cmd_export_graph(opts);
    }

    fmt::print(stderr, "Unknown export format: {}\n", opts.export_format);
    fmt::print(stderr, "Formats: script, compdb, graph\n");
    return EXIT_FAILURE;
}

} // namespace pup::cli
