// SPDX-License-Identifier: MIT
// Copyright (c) 2024 Putup authors

#include "pup/cli/commands.hpp"
#include "pup/cli/context.hpp"
#include "pup/cli/multi_variant.hpp"
#include "pup/cli/output.hpp"
#include "pup/core/layout.hpp"
#include "pup/core/string_utils.hpp"
#include "pup/core/types.hpp"
#include "pup/graph/dag.hpp"
#include "pup/graph/dep_scanner.hpp"
#include "pup/graph/rule_pattern.hpp"
#include "pup/graph/topo.hpp"
#include "pup/index/entry.hpp"
#include "pup/index/reader.hpp"
#include "pup/parser/var_tracking.hpp"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <optional>
#include <set>
#include <unordered_map>
#include <unordered_set>

namespace pup::cli {

namespace {

auto load_index_for_all_deps(
    Options const& opts,
    ProjectLayout const& layout
) -> std::optional<pup::index::Index>
{
    if (!opts.include_all_deps) {
        return std::nullopt;
    }

    auto index_path = layout.index_path();
    if (!std::filesystem::exists(index_path)) {
        fprintf(stderr, "Warning: No index found - run 'putup' first\n");
        return std::nullopt;
    }

    auto index_result = pup::index::read_index(index_path);
    if (!index_result) {
        return std::nullopt;
    }

    index_result->build_edge_indices();
    return std::move(*index_result);
}

auto format_node_id(pup::NodeId id) -> std::string
{
    char buf[32];
    if (node_id::is_command(id)) {
        snprintf(buf, sizeof(buf), "c%zu", node_id::index(id));
    } else {
        snprintf(buf, sizeof(buf), "f%zu", node_id::index(id));
    }
    return buf;
}

auto cmd_export_script(Options const& opts, std::string_view variant_name) -> int
{
    auto scanner_registry = make_scanner_registry();
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
        .scanner_registry = scanner_registry ? &*scanner_registry : nullptr,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fprintf(stderr, "[%.*s] Error: %s\n", static_cast<int>(variant_name.size()), variant_name.data(), result.error().message.c_str());
        return EXIT_FAILURE;
    }

    auto& ctx = *result;
    auto topo = pup::graph::topological_sort(ctx.graph());

    printf("#!/bin/sh\n");
    printf("# Generated by putup\n");
    printf("set -e\n");
    printf("cd \"$(dirname \"$0\")\"\n\n");

    auto output_dirs = std::set<std::string> {};
    for (auto id : ctx.graph().all_nodes()) {
        auto const* node = ctx.graph().get_file_node(id);
        if (!node) {
            continue;
        }
        if (node->type != pup::NodeType::Generated && node->type != pup::NodeType::File) {
            continue;
        }

        auto node_path = ctx.graph().get_full_path(id);
        if (node_path.empty()) {
            continue;
        }

        auto inputs = ctx.graph().get_inputs(id);
        for (auto input_id : inputs) {
            if (node_id::is_command(input_id)) {
                auto path = std::filesystem::path { node_path };
                if (path.has_parent_path()) {
                    auto parent = path.parent_path().string();
                    if (!parent.empty() && parent != ".") {
                        output_dirs.insert(parent);
                    }
                }
                break;
            }
        }
    }

    if (!output_dirs.empty()) {
        printf("# Create output directories\n");
        for (auto const& dir : output_dirs) {
            printf("mkdir -p \"%s\"\n", dir.c_str());
        }
        printf("\n");
    }

    for (auto id : topo.order) {
        if (!node_id::is_command(id)) {
            continue;
        }
        auto const* node = ctx.graph().get_command_node(id);
        if (!node) {
            continue;
        }

        // Skip auto-generated dependency scanning commands (they're for incremental builds only)
        if (node->output_action == graph::OutputAction::InjectImplicitDeps) {
            continue;
        }

        auto source_dir = graph::get_source_dir(ctx.graph().graph(), id);
        auto dir = source_dir.empty() ? std::string { "." } : std::string { source_dir };
        auto cmd = std::string { graph::get_command_str(ctx.graph().graph(), id) };
        printf("(cd \"%s\" && %s)\n", dir.c_str(), cmd.c_str());
    }

    return EXIT_SUCCESS;
}

auto cmd_export_graph(Options const& opts, std::string_view variant_name) -> int
{
    auto scanner_registry = make_scanner_registry();
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
        .scanner_registry = scanner_registry ? &*scanner_registry : nullptr,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fprintf(stderr, "[%.*s] Error: %s\n", static_cast<int>(variant_name.size()), variant_name.data(), result.error().message.c_str());
        return EXIT_FAILURE;
    }

    auto& ctx = *result;
    auto index = load_index_for_all_deps(opts, ctx.layout());

    if (opts.summary) {
        auto commands = ctx.graph().nodes_of_type(pup::NodeType::Command);
        printf("[%.*s] Tupfiles: %zu\n", static_cast<int>(variant_name.size()), variant_name.data(), ctx.parsed_dirs().size());
        printf("[%.*s] Nodes: %zu\n", static_cast<int>(variant_name.size()), variant_name.data(), ctx.graph().node_count());
        printf("[%.*s] Edges: %zu\n", static_cast<int>(variant_name.size()), variant_name.data(), ctx.graph().edge_count());
        printf("[%.*s] Commands: %zu\n", static_cast<int>(variant_name.size()), variant_name.data(), commands.size());

        if (index) {
            auto implicit_count = std::size_t { 0 };
            for (auto const& edge : index->edges()) {
                if (edge.type == pup::LinkType::Implicit) {
                    ++implicit_count;
                }
            }
            printf("[%.*s] Implicit edges: %zu\n", static_cast<int>(variant_name.size()), variant_name.data(), implicit_count);
        }

        if (opts.verbose) {
            printf("[%.*s] Commands:\n", static_cast<int>(variant_name.size()), variant_name.data());
            for (auto id : commands) {
                if (ctx.graph().get_command_node(id)) {
                    auto display_sv = graph::get_display_str(ctx.graph().graph(), id);
                    auto cmd_sv = graph::get_command_str(ctx.graph().graph(), id);
                    auto display = std::string { display_sv.empty() ? cmd_sv : display_sv };
                    printf("[%.*s]   %s\n", static_cast<int>(variant_name.size()), variant_name.data(), display.c_str());
                }
            }
        }
        return EXIT_SUCCESS;
    }

    printf("digraph G {\n");
    printf("  rankdir=LR;\n");

    auto declared_nodes = std::unordered_set<pup::NodeId> {};
    for (auto id : ctx.graph().all_nodes()) {
        declared_nodes.insert(id);

        auto get_label = [&]() -> std::string {
            if (node_id::is_command(id)) {
                auto const* cmd = ctx.graph().get_command_node(id);
                if (!cmd) {
                    return "";
                }
                auto display_sv = graph::get_display_str(ctx.graph().graph(), id);
                auto cmd_sv = graph::get_command_str(ctx.graph().graph(), id);
                return std::string { display_sv.empty() ? cmd_sv : display_sv };
            }
            return ctx.graph().get_full_path(id);
        };
        auto label = escape_dot_label(get_label());

        printf("  %s [label=\"%s\"];\n", format_node_id(id).c_str(), label.c_str());

        for (auto input_id : ctx.graph().get_inputs(id)) {
            printf("  %s -> %s;\n", format_node_id(input_id).c_str(), format_node_id(id).c_str());
        }

        // Output order-only edges (dotted)
        for (auto oo_id : ctx.graph().get_order_only(id)) {
            printf("  %s -> %s [style=dotted color=\"#0088ff\"];\n", format_node_id(oo_id).c_str(), format_node_id(id).c_str());
        }
    }

    if (index) {
        auto implicit_nodes = std::unordered_set<pup::NodeId> {};

        for (auto const& edge : index->edges()) {
            if (edge.type != pup::LinkType::Implicit) {
                continue;
            }

            auto from_id = edge.from;
            auto to_id = edge.to;

            if (declared_nodes.find(to_id) == declared_nodes.end()) {
                continue;
            }

            if (declared_nodes.find(from_id) == declared_nodes.end()) {
                if (implicit_nodes.find(from_id) == implicit_nodes.end()) {
                    implicit_nodes.insert(from_id);
                    auto const* file = index->find_file_by_id(from_id);
                    auto label = file ? escape_dot_label(file->path) : format_node_id(from_id);
                    printf("  %s [label=\"%s\" style=filled fillcolor=\"#f0f0f0\"];\n", format_node_id(from_id).c_str(), label.c_str());
                }
            }

            printf("  %s -> %s [style=dashed color=\"#888888\"];\n", format_node_id(from_id).c_str(), format_node_id(to_id).c_str());
        }
    }

    printf("}\n");
    return EXIT_SUCCESS;
}

auto cmd_export_compdb(Options const& opts, std::string_view variant_name) -> int
{
    auto scanner_registry = make_scanner_registry();
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
        .scanner_registry = scanner_registry ? &*scanner_registry : nullptr,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fprintf(stderr, "[%.*s] Error: %s\n", static_cast<int>(variant_name.size()), variant_name.data(), result.error().message.c_str());
        return EXIT_FAILURE;
    }

    auto& ctx = *result;

    printf("[\n");
    auto commands = ctx.graph().nodes_of_type(pup::NodeType::Command);
    auto first = true;

    for (auto id : commands) {
        auto const* node = ctx.graph().get_command_node(id);
        if (!node) {
            continue;
        }

        auto source_file = std::string {};
        for (auto input_id : ctx.graph().get_inputs(id)) {
            auto input_path = ctx.graph().get_full_path(input_id);
            if (input_path.empty()) {
                continue;
            }
            if (input_path.ends_with(".c") || input_path.ends_with(".cc") || input_path.ends_with(".cpp") || input_path.ends_with(".cxx") || input_path.ends_with(".C") || input_path.ends_with(".S") || input_path.ends_with(".s")) {
                source_file = std::move(input_path);
                break;
            }
        }

        auto output_file = std::string {};
        for (auto output_id : ctx.graph().get_outputs(id)) {
            auto output_path = ctx.graph().get_full_path(output_id);
            if (output_path.empty()) {
                continue;
            }
            if (output_path.ends_with(".o") || output_path.ends_with(".obj")) {
                output_file = std::move(output_path);
                break;
            }
        }

        if (source_file.empty()) {
            continue;
        }

        auto source_dir_sv = graph::get_source_dir(ctx.graph().graph(), id);
        auto working_dir = ctx.layout().source_root;
        if (!source_dir_sv.empty()) {
            working_dir /= source_dir_sv;
        }

        // Convert project-root-relative paths to working-dir-relative
        auto source_abs = ctx.layout().source_root / source_file;
        auto source_rel = std::filesystem::relative(source_abs, working_dir).string();

        auto output_rel = std::string {};
        if (!output_file.empty()) {
            // Generated files exist at output_root
            auto output_abs = ctx.layout().output_root / output_file;
            output_rel = std::filesystem::relative(output_abs, working_dir).string();
        }

        auto cmd_sv = graph::get_command_str(ctx.graph().graph(), id);
        auto args = pup::core::tokenize_shell_command(cmd_sv);
        if (args.empty()) {
            continue;
        }

        if (!first) {
            printf(",\n");
        }
        first = false;

        printf("  {\n");
        printf("    \"directory\": \"%s\",\n", escape_json(working_dir.string()).c_str());

        printf("    \"arguments\": [");
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (i > 0) {
                printf(", ");
            }
            printf("\"%s\"", escape_json(args[i]).c_str());
        }
        printf("],\n");

        printf("    \"file\": \"%s\"", escape_json(source_rel).c_str());
        if (!output_rel.empty()) {
            printf(",\n    \"output\": \"%s\"", escape_json(output_rel).c_str());
        }
        printf("\n  }");
    }

    printf("\n]\n");
    return EXIT_SUCCESS;
}

auto output_var_text(
    std::map<std::string, parser::VarHistory, std::less<>> const& histories
) -> int
{
    for (auto const& [name, history] : histories) {
        printf("%s = %s\n", name.c_str(), history.final_value.c_str());
        printf("  History:\n");
        for (auto const* assign : history.assignments) {
            auto const* prefix = assign->is_effective ? "  " : "# ";
            auto op_str = parser::op_to_string(assign->op);
            printf("  %s%s:%u\t%s %.*s %s", prefix, assign->filename.c_str(), assign->line, assign->name.c_str(), static_cast<int>(op_str.size()), op_str.data(), assign->value_after.c_str());
            if (!assign->is_effective) {
                printf("   (ineffective)");
            }
            printf("\n");
        }
        printf("\n");
    }
    return EXIT_SUCCESS;
}

auto output_var_json(
    std::map<std::string, parser::VarHistory, std::less<>> const& histories,
    std::string_view variant_name
) -> int
{
    printf("{\n");
    printf("  \"variant\": \"%.*s\",\n", static_cast<int>(variant_name.size()), variant_name.data());
    printf("  \"variables\": {\n");

    auto first_var = true;
    for (auto const& [name, history] : histories) {
        if (!first_var) {
            printf(",\n");
        }
        first_var = false;

        printf("    \"%s\": {\n", escape_json(name).c_str());
        printf("      \"value\": \"%s\",\n", escape_json(history.final_value).c_str());
        printf("      \"history\": [\n");

        auto first_assign = true;
        for (auto const* assign : history.assignments) {
            if (!first_assign) {
                printf(",\n");
            }
            first_assign = false;

            auto op_str = parser::op_to_string(assign->op);
            printf("        {\n");
            printf("          \"file\": \"%s\",\n", escape_json(assign->filename).c_str());
            printf("          \"line\": %u,\n", assign->line);
            printf("          \"op\": \"%.*s\",\n", static_cast<int>(op_str.size()), op_str.data());
            printf("          \"value\": \"%s\",\n", escape_json(assign->value_after).c_str());
            printf("          \"effective\": %s\n", assign->is_effective ? "true" : "false");
            printf("        }");
        }

        printf("\n      ]\n");
        printf("    }");
    }

    printf("\n  }\n");
    printf("}\n");
    return EXIT_SUCCESS;
}

auto cmd_export_var(Options const& opts, std::string_view variant_name) -> int
{
    auto log = parser::AssignmentLog {};

    auto on_var_assigned = [&log](
                               std::string_view name,
                               parser::Assignment::Op op,
                               std::string_view value_before,
                               std::string_view value_after,
                               std::string_view filename,
                               std::uint32_t line,
                               std::uint32_t column,
                               bool is_effective
                           ) {
        log.push_back(parser::VarAssignment {
            .name = std::string { name },
            .filename = std::string { filename },
            .line = line,
            .column = column,
            .op = op,
            .value_before = std::string { value_before },
            .value_after = std::string { value_after },
            .is_effective = is_effective,
        });
    };

    auto scanner_registry = make_scanner_registry();
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
        .scanner_registry = scanner_registry ? &*scanner_registry : nullptr,
        .on_var_assigned = on_var_assigned,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fprintf(stderr, "[%.*s] Error: %s\n", static_cast<int>(variant_name.size()), variant_name.data(), result.error().message.c_str());
        return EXIT_FAILURE;
    }

    auto filtered = opts.show_var_filter.empty()
        ? log
        : parser::filter_by_name(log, opts.show_var_filter);

    auto histories = parser::group_by_name(filtered);

    return opts.show_json
        ? output_var_json(histories, variant_name)
        : output_var_text(histories);
}

auto cmd_export_templates(Options const& opts, std::string_view variant_name) -> int
{
    auto scanner_registry = make_scanner_registry();
    auto ctx_opts = BuildContextOptions {
        .verbose = opts.verbose,
        .scanner_registry = scanner_registry ? &*scanner_registry : nullptr,
    };

    auto result = pup::Result<BuildContext> { build_context(opts, ctx_opts) };
    if (!result) {
        fprintf(stderr, "[%.*s] Error: %s\n", static_cast<int>(variant_name.size()), variant_name.data(), result.error().message.c_str());
        return EXIT_FAILURE;
    }

    auto& ctx = *result;
    auto const& graph = ctx.graph().graph();

    // Build template usage map: template_id -> list of command IDs using it
    auto template_usage = std::unordered_map<StringId, std::vector<NodeId>> {};
    auto total_cmd_bytes = std::size_t { 0 };

    for (auto const& cmd : graph.commands) {
        auto cmd_str = graph.strings.get(cmd.command);
        total_cmd_bytes += cmd_str.size();

        if (!is_empty(cmd.template_id)) {
            template_usage[cmd.template_id].push_back(cmd.id);
        }
    }

    auto total_commands = graph.commands.size();
    auto unique_templates = template_usage.size();

    printf("Template Analysis:\n");
    printf("  Commands: %zu\n", total_commands);
    printf("  Unique templates: %zu\n", unique_templates);
    if (unique_templates > 0) {
        printf("  Deduplication ratio: %.1fx\n", double(total_commands) / double(unique_templates));
    }

    // Sort templates by usage count (descending)
    auto sorted_templates = std::vector<std::pair<StringId, std::size_t>> {};
    sorted_templates.reserve(template_usage.size());
    for (auto const& [tid, cmds] : template_usage) {
        sorted_templates.emplace_back(tid, cmds.size());
    }
    std::sort(sorted_templates.begin(), sorted_templates.end(), [](auto const& a, auto const& b) {
        return a.second > b.second;
    });

    // Show top 10 templates
    printf("\nTop templates:\n");
    auto shown = std::size_t { 0 };
    for (auto const& [tid, count] : sorted_templates) {
        if (shown >= 10) {
            break;
        }
        auto template_str = graph.strings.get(tid);
        // Truncate long templates for display
        auto display_str = std::string { template_str };
        if (display_str.size() > 60) {
            display_str = display_str.substr(0, 57) + "...";
        }
        printf("  #%zu (%zu uses): \"%s\"\n", shown + 1, count, display_str.c_str());
        ++shown;
    }

    // Calculate estimated storage savings
    // Current: each command stores full string
    // Template-based: store unique templates + small operand refs per command
    auto unique_template_bytes = std::size_t { 0 };
    for (auto const& [tid, _] : template_usage) {
        unique_template_bytes += graph.strings.get(tid).size();
    }

    // Estimate: template table + 8 bytes per command (template_id + operand offset)
    auto estimated_new_bytes = unique_template_bytes + (total_commands * 8);

    printf("\nStorage estimate:\n");
    printf("  Current command strings: %zu bytes\n", total_cmd_bytes);
    printf("  Unique template strings: %zu bytes\n", unique_template_bytes);
    printf("  Estimated with templates: %zu bytes\n", estimated_new_bytes);
    if (total_cmd_bytes > 0 && estimated_new_bytes < total_cmd_bytes) {
        auto savings = 100.0 * (1.0 - double(estimated_new_bytes) / double(total_cmd_bytes));
        printf("  Potential savings: %.0f%%\n", savings);
    }

    return EXIT_SUCCESS;
}

auto show_single_variant(Options const& opts, std::string_view variant_name) -> int
{
    if (opts.show_format == "script") {
        return cmd_export_script(opts, variant_name);
    }
    if (opts.show_format == "compdb") {
        return cmd_export_compdb(opts, variant_name);
    }
    if (opts.show_format == "graph") {
        return cmd_export_graph(opts, variant_name);
    }
    if (opts.show_format == "var") {
        return cmd_export_var(opts, variant_name);
    }
    if (opts.show_format == "templates") {
        return cmd_export_templates(opts, variant_name);
    }

    fprintf(stderr, "Unknown show format: %.*s\n", static_cast<int>(opts.show_format.size()), opts.show_format.data());
    fprintf(stderr, "Formats: script, compdb, graph, var, templates\n");
    return EXIT_FAILURE;
}

} // namespace

auto cmd_show(Options const& opts) -> int
{
    if (opts.show_format.empty()) {
        fprintf(stderr, "Usage: putup show <format>\n");
        fprintf(stderr, "Formats: script, compdb, graph, var, templates\n");
        return EXIT_FAILURE;
    }

    return for_each_variant(opts, show_single_variant, "Showing");
}

} // namespace pup::cli
